import Foundation

enum ScanReportService {
    static func generateMarkdown(from result: ScanResult) -> String {
        var lines: [String] = []

        lines.append("# DiskAura Scan Report")
        lines.append("")
        lines.append("- **Root**: `\(result.root.path)`")
        lines.append("- **Scanned**: \(result.scannedAt.formatted(date: .long, time: .shortened))")
        lines.append("- **Total size**: \(result.root.sizeBytes.formattedBytes)")

        if let volume = result.volume {
            lines.append("- **Volume total**: \(volume.totalBytes.formattedBytes)")
            lines.append("- **Volume used**: \(volume.usedBytes.formattedBytes)")
            lines.append("- **Volume free**: \(volume.freeBytes.formattedBytes)")
        }

        lines.append("")
        lines.append("## Top-level breakdown")
        lines.append("")
        lines.append("| Folder | Size | Tag |")
        lines.append("|---|---|---|")
        for child in result.root.sortedChildren.prefix(50) {
            lines.append("| `\(child.name)` | \(child.sizeBytes.formattedBytes) | \(child.tag.label) |")
        }

        if !result.deniedPaths.isEmpty {
            lines.append("")
            lines.append("## Permission-denied paths (\(result.deniedPaths.count))")
            lines.append("")
            for path in result.deniedPaths.prefix(30) {
                lines.append("- `\(path)`")
            }
        }

        if !result.skippedPaths.isEmpty {
            lines.append("")
            lines.append("## Skipped (different volume/mount) paths (\(result.skippedPaths.count))")
            lines.append("")
            for path in result.skippedPaths.prefix(30) {
                lines.append("- `\(path)`")
            }
        }

        lines.append("")
        lines.append("---")
        lines.append("*Generated by DiskAura*")

        return lines.joined(separator: "\n")
    }
}
